/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Zelp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {


    @Test
    void testShop(){
        Shop carrefour = new Shop("Carrefour" , "exists in Amman" , 5);
        assertEquals("Carrefour shop is exists in Amman , and has $$$$$ , 0.0 stars review" , carrefour.toString());
    }
    @Test
    void testShopReview(){
        Shop cityMall = new Shop("City Mall" , "exists in Amman" , 5);
        cityMall.addReview("Qusay" , 4);
        assertEquals("City Mall shop is exists in Amman , and has $$$$$ , 4.0 stars review" , cityMall.toString());
    }
    @Test
    void testTheater(){
        Theater primeCinema = new Theater("Prime Cinema" , "Interstellar");
        primeCinema.addMovie("Inception");
        assertEquals("Prime Cinema is currently showing [Interstellar, Inception] movies" , primeCinema.toString());
    }
    @Test
    void testTheaterReview(){
        Theater  primeCinema = new Theater("Prime Cinema" , "Interstellar");
        primeCinema.addMovie("Inception");
        primeCinema.addReview("qusay" , 1);
        primeCinema.addReview("omar" , 4);
        assertEquals("{qusay=1.0, omar=4.0}" , primeCinema.getReviews());
    }

}
