/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.lang.reflect.Array;
import java.util.*;

import java.io.*;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        FileInputStream in = null;
        FileOutputStream out = null;

        try {
            in = new FileInputStream("../resources/gates.js");
            out = new FileOutputStream("output.txt");

            int c;
            while ((c = in.read()) != -1) {
                out.write(c);
                if ((char)c == '\n') {
                    System.out.println("We found the newline!!");
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
//            if (in != null) {
//                in.close();
//            }
//            if (out != null) {
//                out.close();
            }
        }

}
